import {
	Archive,
	BarChart3,
	Edit3,
	File,
	FileText,
	Globe,
	type Icon,
	Image,
	LayoutDashboard,
	LifeBuoy,
	Link,
	List,
	type LucideIcon,
	Menu,
	MessageSquare,
	Palette,
	Plug,
	Settings,
	ShoppingCart,
	Users,
} from '@lucide/vue'

const iconMap: Record<string, LucideIcon | typeof Icon> = {
	'dashicons-dashboard': LayoutDashboard,
	'dashicons-admin-post': FileText,
	'dashicons-admin-page': File,
	'dashicons-admin-appearance': Palette,
	'dashicons-admin-plugins': Plug,
	'dashicons-admin-users': Users,
	'dashicons-admin-settings': Settings,
	'dashicons-admin-comments': MessageSquare,
	'dashicons-admin-media': Image,
	'dashicons-admin-links': Link,
	'dashicons-admin-generic': FileText,
	'dashicons-admin-tools': Settings,
	'dashicons-admin-customizer': Edit3,
	'dashicons-menu': Menu,
	'dashicons-menu-alt': Menu,
	'dashicons-menu-alt2': Menu,
	'dashicons-menu-alt3': Menu,
	'dashicons-cart': ShoppingCart,
	'dashicons-translation': Globe,
	'dashicons-archive': Archive,
	'dashicons-admin-site': Globe,
	'dashicons-admin-home': LayoutDashboard,
	'dashicons-admin-network': Globe,
	'dashicons-admin-multisite': Globe,
	'dashicons-welcome-write-blog': Edit3,
	'dashicons-welcome-add-page': FileText,
	'dashicons-welcome-view-site': Globe,
	'dashicons-welcome-widgets-menus': Menu,
	'dashicons-format-aside': File,
	'dashicons-format-gallery': Image,
	'dashicons-format-video': Globe,
	'dashicons-format-audio': Globe,
	'dashicons-format-chat': MessageSquare,
	'dashicons-format-status': FileText,
	'dashicons-format-image': Image,
	'dashicons-format-quote': FileText,
	'dashicons-format-links': Link,
	'dashicons-post-formats': Edit3,
	'dashicons-camera': Image,
	'dashicons-images-alt2': Image,
	'dashicons-video-alt3': Globe,
	'dashicons-editor-code': File,
	'dashicons-editor-ul': List,
	'dashicons-editor-ol': List,
	'dashicons-editor-expand': Menu,
	'dashicons-chart-area': BarChart3,
	'dashicons-chart-bar': BarChart3,
	'dashicons-chart-line': BarChart3,
	'dashicons-chart-pie': BarChart3,
	'dashicons-money': ShoppingCart,
	'dashicons-backup': Archive,
	'dashicons-shield': Plug,
	'dashicons-performance': BarChart3,
	'dashicons-location': Globe,
	'dashicons-location-alt': Globe,
	'dashicons-store': ShoppingCart,
	'dashicons-sos': LifeBuoy,
	'dashicons-id': Users,
	'dashicons-groups': Users,
	'dashicons-businessperson': Users,
	'dashicons-vault': Archive,
	'dashicons-download': Archive,
	'dashicons-cloud': Archive,
	'dashicons-cloud-upload': Archive,
	'dashicons-clipboard': File,
	'dashicons-table-row-after': List,
	'dashicons-list-view': List,
}

export function getIcon(dashicon?: string): LucideIcon {
	return ((dashicon && iconMap[dashicon]) || FileText) as LucideIcon
}
